django_login_out/urls.py
from django.contrib import admin
from django.urls import path,include
from login_out import views

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('login_out/' , include('login_out.urls')),
    path('logout/' , views.user_logout , name = 'logout'),
    path('admin/', admin.site.urls),
]

login_out/urls.py
from django.urls import path
from login_out import views


app_name = 'login_out'

urlpatterns = [
    path('register/' , views.register , name = 'register'),
    path('user_login/' , views.user_login , name = 'user_login'),
]

login_out/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User , on_delete = models.CASCADE)

    name = models.CharField(max_length = 256)

    DOB = models.CharField(max_length = 100)

    def __str__(self):
        return self.name

login_out/forms.py
from django import forms
from django.contrib.auth.models import User
from login_out.models import UserProfileInfo

class User_Form(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username' , 'email', 'password')

class User_Profile_Form(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('name' , 'DOB')


class login_form(forms.Form):
    USERNAME = forms.CharField()
    PASSWORD = forms.CharField(widget = forms.PasswordInput())

login_out/views.py
from django.shortcuts import render
from login_out.forms import User_Form , User_Profile_Form , login_form

#LOGIN AND LOGOUT
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request , 'login_out/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = User_Form(request.POST)
        profile_form = User_Profile_Form(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            profile.save()

            registered = True
            print("REGISTRATION SUCCESSFULL!!")
            print("USERNAME : " + user.username)
            print('PASSWORD(HASHED) : ' + user.password)
            print('NAME : ' + profile.name)
        else:
            print("FORM INVALID")
            print(user_form.errors , profile_form.errors)

        username = user_form.cleaned_data['username']
        password = user_form.cleaned_data['password']

        user1 = authenticate(username=username , password=password)

        login(request , user)
        return HttpResponseRedirect(reverse('index'))


    else:
        user_form = User_Form()
        profile_form = User_Profile_Form()

    return render(request , 'login_out/register.html' , {'user_form' : user_form,
                                                        'profile_form' : profile_form,
                                                        'registered' : registered})

def user_login(request):
    form = login_form()

    if request.method == 'POST':
        form = login_form(request.POST)

        if form.is_valid():
            username = form.cleaned_data['USERNAME']
            password = form.cleaned_data['PASSWORD']

            user = authenticate(username=username , password=password)

            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('USER IS INACTIVE')

        else:
            print('SOMEONE TREID TO LOGIN : ')
            print('USERNAME : {}       PASSWORD : {}'.format(username,password))
            return HttpResponse('INVALID LOGIN CREDENTIALS!!')

    else:
        return render(request , 'login_out/login.html' , {'form' : form})

login_out/templates/login_out/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-nav">
          <a href="{% url 'index' %}" class="navbar-brand">MICROSOFT</a>
          <a href="{% url 'admin:index' %}" class="nav-item nav-link">ADMIN</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="nav-item nav-link" >LOGOUT</a>
          {% else %}
            <a href="{% url 'login_out:register' %}" class="nav-item nav-link">REGISTER</a>
            <a href="{% url 'login_out:user_login' %}" class="nav-item nav-link" >LOGIN</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <br>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

login_out/templates/login_out/index.html
{% extends 'login_out/base.html' %}
  {% block body_block %}

    <div class="jumbotron">
      <h1 class="display-4">WELCOME TO MICROSOFT'S SUBSTITUTE WEBSITE</h1>
      {% if user.is_authenticated %}
        <h2>WELCOME TO OUR WEBSITE : <strong><em>{{ user.username }}</em></strong></h2>
      {% else %}
        <h2>YOU ARE NOT LOGGED IN</h2>
      {% endif %}
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>


  {% endblock %}

login_out/templates/login_out/login.html
{% extends 'login_out/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h1 class="display-4">PLEASE ENTER CREDENTIALS!!</h1>
      <form action="{% url 'login_out:user_login' %}" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-lg">LOGIN</button>
      </form>
    </div>
  {% endblock %}

login_out/templates/login_out/register.html
{% extends 'login_out/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1 class="display-4">THANK YOU FOR REGISTERING WITH US!!</h1>
      {% else %}
        <h1 class="display-4">PLEASE SIGNUP HERE</h1>
        <br>
        <form method="POST">
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-lg">REGISTER</button>
        </form>
      {% endif %}
    </div>
  {% endblock %}